# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_manage', '0003_experiment_exp_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmimage',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
